# Generated by Django 4.1.1 on 2022-09-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('gender_user', models.CharField(max_length=15)),
                ('password_user', models.CharField(max_length=100)),
            ],
        ),
    ]
