# Generated by Django 4.1.1 on 2022-09-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
    ]
